### ISSUE TITLE
Node-red instance websocket connection proxying has some issue

### ISSUE THREAD

**Issue by rmvpaps** [muka/redzilla#10]
Hi, In Node-red instance opened from browser as http://instancename.redzilla.localhost:3000, websocket  connection to ws://instancename.redzilla.localhost:3000/comms is showing  error - 404
I did the following steps on my ubuntu 16.04
- git clone redzilla
- docker-compose up -d
- update /etc/hosts - 127.0.0.1    redzilla.localhost
- Create a new instance -  curl -X POST http://redzilla.localhost:3000/v2/instances/instancename 
- update /etc/hosts - 127.0.0.1    instancename.redzilla.localhost
- GET http://instancename.redzilla.localhost:3000 

Is anything more to be done to get it to work? I did see code for websocket proxy, So I assume it is already taken care of and I am missing some configuration steps.

**Comment by muka** [comment]
Hi
You should not set  /etc/hosts as it will be handled by the system.

Websocket is managed so should work.. can you retry and report so I can try
to reproduce on my machine

Thanks


sent from my phone

Il lun 23 apr 2018, 13:39 rmvpaps <notifications@github.com> ha scritto:

**Comment by rmvpaps** [comment]
Hi,
Loos like I am missing something important. I am working on the master branch. Without setting /etc/hosts for redzilla.localhost and instancename.redzilla.localhost, I am getting "could not resolve host - redzilla.localhost" for redzilla APIs using curl. So if I set it for just redzilla.localhost, then I am getting the same error (server not found) when trying to get node-red from browser with instancename.redzilla.localhost.

**Comment by rmvpaps** [comment]
I think it is my browsers problem - Its not checking /etc/hosts but checking the main DNS servers. I installed in another system and it works fine for chrome and ie.  Sorry for taking your time. Thank you.

But I still have no idea how to do this without changing /etc/hosts or otherwise asking network admin to add dns resolution for redzilla.localhost

**Comment by muka** [comment]
On my pc it just resolve *.localhost to 127.0.0.1, so http://hello.redzilla.localhost:3000 just spawn a new node-red instance..

Let me know if you find a solution so we can fix the bug or at least add a reference in  the docs

Thanks!
