### ISSUE TITLE
Is there some documentation on authentication feature?

### ISSUE THREAD

**Issue by rmvpaps** [muka/redzilla#11]
I modified config.example.yml to data folder and added REDZILLA_CONFIG=/custom/config.example.yml
and added volume in docker-compose.yml ./custom:/custom

AuthType: http
#HTTP based auth / ACL will performa a POST request to an endpoint and allow on 2xx or deny on other responses
#Body is a go template
AuthHttpMethod: POST
AuthHttpUrl: http://192.168.0.235:1880/redzilla/user
AuthHttpHeader: Authorization
AuthHttpBody: "{ \"name\": \"{{.Name}}\", \"url\": \"{{.Url}}\", \"method\": \"{{.Method}}\" }"

After running redzilla, and trying to open node-red instance, I could not find any requests logged to the server's endpoint.(Its a standalone node-red in another system). Do we have to pass any parameter like name or something?

**Comment by muka** [comment]
Try checking here

**Comment by rmvpaps** [comment]
Hi,
I finally got this to work. after i gave docker network ip address of the host machine in the authhttp url instead of IP address of ethernet. Host machine runs the server that authenticates.

I found another issue - For creating the Go template, its taking AuthhttpHeader instead of AuthHttpBody. So the parsed value in body is actually not very useful - Its always Authorization or something.

**Comment by muka** [comment]
Good one! Need to take some time to fix, thanks

**Comment by muka** [comment]
Closing for now, reopen if needed
