### ISSUE TITLE
Custom Image for Node-RED coniguration not working

### ISSUE THREAD

**Issue by RohanAsmat** [muka/redzilla#14]
Hi Muka,

Thank you for an update @muka,
Can you please provide detailed steps of how to achieve this, as what I have done and which still doesn't work is as follows:

    1. Uncommenting the image name from docker-compose to opny/redzilla

    2. Renaming config.example.yml to config.yml

    3. Updating ImageName in config.yml to rohanasmat/node-red-dashboard-plus-nodes:latest which is pulled from docker hub and it contains additional node palette for Node-RED.

    4. Running docker-compose up

I am getting the following error:
`
Building redzilla
Step 1/4 : FROM scratch
--->
Step 2/4 : ENV GIN_MODE=release
---> Using cache
---> 714a5d49dd7e
Step 3/4 : COPY ./redzilla /redzilla
ERROR: Service 'redzilla' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder893982847/redzilla: no such file or directory

`

Please let me know what I might be doing wrong my image contains some Node-RED dashboard nodes etc.

Best Regards,
Muhammad Rohan Ali Asmat

**Comment by muka** [comment]
Hi Roahn
I added a few adjustment to the code. Try like this

1. Run a `git pull` in the repo and `docker-compose pull` to get the latest redzilla image
2. In `docker-compose.yml` edit `IMAGE_NAME` with your local image name.
3. Follow the introduction in the repo `README` to create and open an instance

Let me know how it goes

**Comment by RohanAsmat** [comment]
Hi @muka,

Thank you very much for an update the custom Image configuration works without a trouble now! 

Many thanks for the repository and the feature! 

Best Regards,
Muhammad Rohan Ali Asmat
