### ISSUE TITLE
Node-Red Instance with Configuration and Flows Pre-Loaded

### ISSUE THREAD

**Issue by ghost** [muka/redzilla#15]
Respected @muka,

Many thanks for the repository this is really helpful, may I ask is there a way to 
generate a Node-RED instance with a custom settings.js that can be used to set credentials and with a flow file so that the instance is preloaded. 

One way could be to use images as required, but can this code base support such a case? 

Plus, if that is not the case currently, would it be possible to do so? 

Thank you in advance! 

Best Regards, 
Muhammad Rohan Ali Asmat

**Comment by muka** [comment]
Hi @RohanAsmat 

have you checked [node-red-admin](https://nodered.org/docs/node-red-admin) ?

I think it can help you in setting some configurations.

To handle authentication and further customization take [a look to this repo](https://github.com/raptorbox/raptor-workflow-manager) for an example, you will need to code yourself I guess

Best

**Comment by ghost** [comment]
Hi @muka,

Thank you for your replies, yes I am using node-red-admin, would have a look on the other repository you pointed out.

Best Regards,
Muhammad Rohan Ali Asmat
