### ISSUE TITLE
can we install the rezilla v2.0 with by README.md in the master?

### ISSUE THREAD

**Issue by huangliuzhou** [muka/redzilla#4]

**Comment by muka** [comment]
Hi @huangliuzhou, I will update this issue as soon there is an initial working version

**Comment by huangliuzhou** [comment]
OK, Thank you so much! Please let me know when the first working version is update, i am holding a company in china for IOT ,I wish we can corporate in the future.

**Comment by huangliuzhou** [comment]
By the way ,I am willing to do the beta testing very much.

**Comment by muka** [comment]
Thank you a lot, I will give an update as soon as `v2` is working

**Comment by muka** [comment]
@huangliuzhou I just released the v2 as promised. 
Give it a try and feel free to report any issue you found. Thanks!
