### ISSUE TITLE
import dashboard failed

### ISSUE THREAD

**Issue by brusand** [muka/redzilla#5]
Hi,

First, congratulation for your work, i ll try to integrate it. But i have an issue with adding node-red dashboard.

i went into node-red folder, i do npm i node-red-dashboard -s , every things is ok
but after grunt build, no dashboard are seen in the node-red editor, what i missed ?

thks
Bruno

**Comment by muka** [comment]
Hi Bruno,
depending on your configuration you may have to rebuild the docker
container. There is a script for it.



2017-03-09 22:58 GMT+01:00 brusand <notifications@github.com>:

**Comment by brusand** [comment]
Hi muka,
sorry but i try to update to latest version of node-red and add the dashboard but build-docker.sh have some erros/warn but at the end he said ok.

when i launch node bin/redzilla run, the server is started but have this kind of error 

debug: Selected port 3014
silly: Base config updated
debug: {"name":"hello-world","uid":"2095312189753de6ad47dfe20cbe97ec","port":3014,"path":"","dir":"./instances/2095312189753de6ad47dfe20cbe97ec","settings":{"uiPort":3014,"flowFile":"flow.json","flowFilePretty":true,"httpRoot":"","userDir":"./instances/2095312189753de6ad47dfe20cbe97ec","nodesDir":"./custom-nodes","uiHost":"127.0.1.1"},"created":"2017-03-13T21:59:50.839Z","updated":"2017-03-13T22:00:17.728Z","status":"started","host":"127.0.1.1","started":"2017-03-13T22:00:15.177Z"}
silly: Instance setup
debug: Write file /Users/bruno/redzilla/instances/2095312189753de6ad47dfe20cbe97ec/settings.js
info: Process info name=hello-world, uid=2095312189753de6ad47dfe20cbe97ec, port=3014, path=, dir=./instances/2095312189753de6ad47dfe20cbe97ec, uiPort=3014, flowFile=flow.json, flowFilePretty=true, httpRoot=, userDir=./instances/2095312189753de6ad47dfe20cbe97ec, nodesDir=./custom-nodes, uiHost=127.0.1.1, created=2017-03-13T21:59:50.839Z, updated=2017-03-13T22:00:17.728Z, status=started, host=127.0.1.1, started=2017-03-13T22:00:15.177Z
debug: Write file /Users/bruno/redzilla/instances/cache.json
warn: node-red has not start in time
Unhandled rejection Error: node-red has not start in time
    at Timeout.<anonymous> (/Users/bruno/redzilla/lib/util.js:219:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

warn: [hello-world] (node:1385) DeprecationWarning: sys is deprecated. Use util instead.
warn: [hello-world] 
warn: node-red has not start in time
Unhandled rejection Error: node-red has not start in time
    at Timeout.<anonymous> (/Users/bruno/redzilla/lib/util.js:219:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

warn: node-red has not start in time
Unhandled rejection Error: node-red has not start in time
    at Timeout.<anonymous> (/Users/bruno/redzilla/lib/util.js:219:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

warn: node-red has not start in time
Unhandled rejection Error: node-red has not start in time
    at Timeout.<anonymous> (/Users/bruno/redzilla/lib/util.js:219:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

warn: node-red has not start in time
Unhandled rejection Error: node-red has not start in time
    at Timeout.<anonymous> (/Users/bruno/redzilla/lib/util.js:219:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

^Cinfo: Stopping..
debug: Stopping bruno
warn: @TODO: implement localhost.status
silly: Instance bruno is `running`
debug: Stopping hello-world
Unhandled rejection Error: Instance does not exists


any idea , i am on a mac 10.9 and docker toolbox.

Bruno

**Comment by brusand** [comment]
and same with any of examples

**Comment by muka** [comment]
I see, I am working on a v2 branch with updated dips so I am not going to
support this version anymore.
I suggest to wait for that one

**Comment by brusand** [comment]
humm i am look forward to use the first working version !

bruno

**Comment by muka** [comment]
Hi @brusand I just released v2. Please give it a try and feel free to report any issue you may find.

Regarding this specific issue, you should be able to use the node red core api to add a module (I have not tried it myself yet)

See here for `POST /nodes` http://nodered.org/docs/api/admin/methods/
I will add additional APIs to do such operations in batch on all instances soon

Thanks
