### ISSUE TITLE
Ensure network exists on startup

### ISSUE THREAD

**Issue by muka** [muka/redzilla#9]
When started, check if the specified network exists or eventually create it.

**Comment by rmvpaps** [comment]
Hi, I was trying to run the instance create on v2.0 branch and I got -{"code":500,"message":"Internal Server Error"}. The docker logs on redzilla container shows
time="2018-04-10T04:22:46Z" level=info msg="Container create mynew"
time="2018-04-10T04:22:46Z" level=error msg="Internal Error: Error response from daemon: network redzilla not found"
My docker network ls shows
f21742fa706d        redzilla_redzilla   bridge              local
67e9a7a6ce24        redzilla_webproxy   bridge              local

The folder name prefix is used. Is this the same issue or some networking issue on my side? (I had installed the docker(17.12.1-ce) and docker compose(1.19.0) as given in docker site)

**Comment by muka** [comment]
Hi
You can Try with

docker network create redzilla

Or look at the config file / environment vars to set another network name
from those that exists in docker

Need to review this to make it start with default settings.

 Thanks

sent from my phone


Il mar 10 apr 2018, 06:41 rmvpaps <notifications@github.com> ha scritto:
